### ISSUE TITLE
The website is not reachable

### ISSUE THREAD

**Issue by shubhamkumar13** [sn99/rust-practise-questions#12]
The link : https://sn99.github.io/rust-practise-questions/ produces a 404
![Screenshot from 2022-11-02 13-42-08](https://user-images.githubusercontent.com/13629677/199434978-6aef7c69-c4aa-4090-a519-76fef647704e.png)

is there a way I can build this temporarily?

**Comment by sn99** [comment]
@shubhamkumar13 It should now be reachable on https://rust-unofficial.github.io/rust-practise-questions/, it was recently moved to the new address

**Comment by shubhamkumar13** [comment]
Thanks @sn99 :) !!
